http_addrs:
    - "http://localhost:8080"
    - "http://localhost:8081"
    - "http://localhost:8082"
grpc_addrs:
    - "localhost:8080"
    - "localhost:8081"
    - "localhost:8082"
initial_delay: 2s
heartbeat_duration: 1s
